import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Form from "../components/form";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Form Handeling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </div>
  );
}
